// Generated by CoffeeScript 2.2.4
(function() {
  this.CircularScale = class CircularScale {
    // vis - visualization container id (without preceding "#")
    // id - id of the legend  (without preceding "#")
    // scale - scaling function
    // values - array of values to reflet
    // anchor - where to pin it
    constructor(vis, id, title, scale, values, anchor) {
      this.exists = this.exists.bind(this);
      this.compute_parameters = this.compute_parameters.bind(this);
      this.elements = this.elements.bind(this);
      // create the scale from scratch
      this.create = this.create.bind(this);
      this.enter = this.enter.bind(this);
      this.refresh = this.refresh.bind(this);
      this.exit = this.exit.bind(this);
      this.update = this.update.bind(this);
      this.vis = vis.removeLeadHash();
      this.anchor = anchor;
      this.id = id.removeLeadHash();
      this.scale = scale;
      this.values = values.sort(d3.descending);
      this.title = title;
      this.fixed_formatter = d3.format(",d");
      this.delay = 750;
      this.create();
    }

    exists() {
      return $(`#${this.id}`).length > 0;
    }

    compute_parameters() {
      var radiusMax;
      // circles centered relative to the anchor.
      radiusMax = this.scale(this.values[0]);
      this.center = {
        x: this.anchor.x + radiusMax,
        y: this.anchor.y + radiusMax
      };
      this.width = radiusMax * 2 + 10;
      this.height = this.width;
      
      // extra horizontal passing to display text
      this.padding = 100;
      return this.radius = this.height / 2;
    }

    elements() {
      return [this.svg.selectAll("circle").data(this.values), this.svg.selectAll("line").data(this.values), this.svg.selectAll("text").data(this.values)];
    }

    create() {
      var circles, html, lines, style, text, title;
      this.compute_parameters();
      style = `left:${this.anchor.x}px; top:${this.anchor.y}px; position:relative; width:${this.width + this.padding}px;`;
      title = `<p>${this.title}</p>`;
      html = '<div id="' + this.id + '" style="' + style + '">' + title + '</div>';
      $('#' + this.vis).append(html);
      this.svg = d3.select(`#${this.id}`).append("svg").attr("id", "svg_scale").style("position", "relative");
      [circles, lines, text] = this.elements();
      return this.enter(circles, lines, text);
    }

    enter(circles, lines, text) {
      var that;
      that = this;
      if (this.svg.attr("width") < this.width + this.padding) {
        this.svg = this.svg.attr("width", this.width + this.padding).attr("height", this.height + 10);
      }
      circles.enter().append("circle").attr("class", "scaleCircle").attr("cx", this.width / 2).attr("cy", function(d) {
        return 2 * that.radius - that.scale(d);
      }).attr("r", function(d) {
        return 0;
      });
      lines.enter().append("line").attr("class", "scaleCircle").attr("x1", function(d) {
        return that.width / 2;
      }).attr("y1", function(d) {
        return 2 * (that.radius - that.scale(d));
      }).attr("x2", function(d) {
        return that.width / 2;
      }).attr("y2", function(d) {
        return 2 * (that.radius - that.scale(d));
      });
      text.enter().append("text").attr("text-anchor", "end").attr("class", "scaleCircleLabel").text(function(d) {
        return that.fixed_formatter(d);
      }).attr("x", this.width / 2).attr("y", function(d) {
        return 2 * (that.radius - that.scale(d));
      });
      return this.update(circles, lines, text);
    }

    refresh(scale, values) {
      var circles, lines, text;
      this.scale = scale;
      this.values = values.sort(d3.descending);
      this.compute_parameters();
      [circles, lines, text] = this.elements();
      this.enter(circles, lines, text);
      this.exit(circles, lines, text);
      return this.update(circles, lines, text);
    }

    exit(circles, lines, text) {
      var that;
      that = this;
      circles.exit().transition().duration(this.delay).ease("linear").attr("r", 0).remove();
      lines.exit().remove();
      return text.exit().remove();
    }

    update(circles, lines, text) {
      var that;
      that = this;
      circles.transition().duration(this.delay).attr("cx", this.width / 2).attr("cy", function(d) {
        return 2 * that.radius - that.scale(d);
      }).attr("r", function(d) {
        return that.scale(d);
      });
      lines.transition().duration(this.delay).attr("class", "scaleCircle").attr("x1", function(d) {
        return that.width / 2;
      }).attr("y1", function(d) {
        return 2 * (that.radius - that.scale(d));
      }).attr("x2", function(d) {
        return that.width + that.padding / 2;
      }).attr("y2", function(d) {
        return 2 * (that.radius - that.scale(d));
      });
      return text.transition().duration(this.delay).text(function(d) {
        return that.fixed_formatter(d);
      }).attr("x", function(d) {
        return that.width + that.padding / 2;
      }).attr("y", function(d) {
        return 2 * (that.radius - that.scale(d));
      });
    }

  };

}).call(this);
