// Generated by CoffeeScript 2.2.4
(function() {
  this.ViewModel = class ViewModel {
    constructor() {
      this.violent = ["murder", "rape", "robbery", "assault"];
      this.property = ["arson", "burglary", "larceny", "vehicle_theft"];
      this.crime = ko.observableArray($.bbq.getState("crimes") == null ? [] : $.bbq.getState("crimes").split(";"));
      this.capitalize = function(text) {
        return text.split('_').map(function(t) {
          return t.slice(0, 1).toUpperCase() + t.slice(1);
        }).join(' ');
      };
      this.crimes = [
        {
          crime: this.violent,
          type: "violent"
        },
        {
          crime: this.property,
          type: "property"
        }
      ];
      this.ofType = (type) => {
        var res;
        res = $.grep(this.crimes, function(c) {
          return c.type === type;
        })[0];
        return this.crimes.indexOf(res);
      };
      // clicked checkbox
      this.get_crimes = () => {
        $.bbq.pushState({
          crimes: this.crime().join(';')
        });
        return true;
      };
    }

  };

}).call(this);
